### ISSUE TITLE
MountainBikeRide sport for Rides selection must by manually added into calendar URL

### ISSUE THREAD

**Issue by obriencj** [strautomator/web#21]
When selecting the Rides sport type for the calendar export in the web UI, it crafts a URL with a sports filter containing values that appear to be limited to those from the ActivityType enumeration, only `Ride,EBikeRide,VirtualRide`. Unfortunately, this then omits mountain bike rides from the calendar.

If you want to see a mountain bike ride in the calendar, you need to manually edit the URL to include values from the SportType enum instead, eg. `Ride,MountainBikeRide`. This makes both regular rides and mountain bike rides appear in the calendar.

https://developers.strava.com/docs/reference/#api-models-ActivityType
https://developers.strava.com/docs/reference/#api-models-SportType

Thank you so much for this service, I really appreciate having these entries in my calendar!

**Comment by igoramadas** [comment]
Hi @obriencj that's by design, for now, as on the UI there's space for only 3 options. In fact, looking at the logs, I assume that most people seem to get it easily that you can just adjust the URL with your own preferences.

Eventually I'll update the UI and allow users to specifically select which sport types they want. Probably early next year.
