### ISSUE TITLE
Preferences not saved

### ISSUE THREAD

**Issue by Glennmen** [strautomator/web#25]
Since about a week I noticed that my preferences are reset. 
I set them back, manual sync activity again, language and weather provider seem to be correct but not AI provider. It keeps using Gemini, even when I have set it to OpenAI.

Then after some time, not sure how long, it gets reset again and I have to change all my preferences.

**Comment by igoramadas** [comment]
Hi Glenn, this is a known issue that I completely forgot to get sorted some days ago. This will be fixed with the next release (happening at the weekend, at the latest, but possibly earlier). Sorry for the trouble.

Root cause: OpenAI is treated as the default provider on the user preferences handler, so when you select it, the value will be simply removed from your preferences. Then it will randomly select between OpenAI or Gemini when doing the actual prompts, because there's no value set for your user.

**Comment by igoramadas** [comment]
https://github.com/strautomator/web/commit/1eec24e1cb75f608c083e2266ac7f79fdb691613

**Comment by Glennmen** [comment]
@igoramadas Not sure how that explains why my other preferences also being cleared 🤔

**Comment by igoramadas** [comment]
This I am not aware. I'll investigate the logs and come back to you once I find out what's going on.
